### ISSUE TITLE
Pull in changes from mihaip/utm-stripper

### ISSUE THREAD

**Issue by liam-m** [grahams/safari-utm-stripper#4]
Hey @grahams, I've been using [mihaip/utm-stripper](https://github.com/mihaip/utm-stripper) which is a fork of [jparise/chrome-utm-stripper](https://github.com/jparise/chrome-utm-stripper) with some improvements (some of which were authored by me). 

Would you be interested in including any of these improvements in this extension? The ones I can see are:

* Fixed URL parsing when there are parameters after UTM ones - https://github.com/mihaip/utm-stripper/commit/4561b7d89d8de0c9febc5a8477b278ce395c099e (not sure if this affects this extension)
* Strips utm_reader - https://github.com/mihaip/utm-stripper/commit/52aa2788f9a0f64f6bda048fbd464b713781923e
* Strips YouTube URLs - https://github.com/mihaip/utm-stripper/commit/2e506321bbeb4609078be415bb07633296148f4c, https://github.com/mihaip/utm-stripper/commit/f1bf60c699ee6b09ac119c0fbe84022fc9b8338c and https://github.com/mihaip/utm-stripper/commit/b202a3488236357ff2e87aab7cc07308d39ac260
* Strips MailChimp tracking parameters - https://github.com/mihaip/utm-stripper/commit/f1bf60c699ee6b09ac119c0fbe84022fc9b8338c

I think it would mainly be copying code from [background.js](https://github.com/mihaip/utm-stripper/blob/master/extension/background.js) to [charisma.js](https://github.com/grahams/safari-utm-stripper/blob/master/safari-utm-stripper.safariextension/charisma.js).

The extension also has some tests you could use to verify everything works.

I'm trying to use Safari as my default browser on El Cap so anything I can do to reach extension parity with Chrome would be great. I'd be happy to implement/test any changes. I'm not currently a member of the ADP (I was a member of the Safari one but it's now been integrated to the main one, which costs money) which I think is required to be able to develop an extension.

**Comment by grahams** [comment]
I'll definitely take a look at what it'd take to port these changes over....  Of course, I'd also accept pull requests if you wanted to do the work yourself.

I have an ADP membership I can use to sign and release the final version of the extension..  I'm not sure if you need ADP for the develop/test cycle, though..

**Comment by liam-m** [comment]
That's great, thanks a lot!

I'm new to Safari extension development but it looks to me like you do:

<img width="520" alt="screen shot 2015-07-13 at 09 23 35" src="https://cloud.githubusercontent.com/assets/3648097/8645623/f41860d8-2940-11e5-8208-5fca3e551566.png">

I can't install or build package as I don't have a developer certificate.

**Comment by liam-m** [comment]
Made another change for YouTube URLs - https://github.com/mihaip/utm-stripper/commit/dc63613f2cdbe3db316b1fbff6fe02d5a2f04b06

**Comment by grahams** [comment]
A bit of a delay, but I did eventually get around to it.  Let me know if there are any issues.

If the auto-update isn't working, or is slow, you can grab the latest release here:
http://dosburros.com/dev/safari-utm-stripper/safari-utm-stripper-2.0.3.safariextz

**Comment by liam-m** [comment]
<img width="532" alt="screen shot 2015-12-13 at 14 33 41" src="https://cloud.githubusercontent.com/assets/3648097/11767478/85a1859c-a1a6-11e5-94ef-963f796cfbec.png">

**Comment by grahams** [comment]
That's strange....  I just uninstalled it and reinstalled it, downloading it directly from the URL above, and other than the warning that it didn't come from the apple gallery it installed fine...  Hrm.

**Comment by grahams** [comment]
@liam-m Even more strange is that a friend was also just able to install it on his machine..  Maybe download and try again?

**Comment by liam-m** [comment]
Autoupdate hadn't picked up the new version and I was trying to get it to update by installing it. Uninstalling and reinstalling worked so I assume it isn't able to update by installing on top - i.e. you can't install an extension that you already have an older version of.

**Comment by liam-m** [comment]
Just noticed the YouTube ones aren't working for me - do they work for you?

**Comment by grahams** [comment]
I just pushed a new version, 2.0.4, let me know if it helps...

http://dosburros.com/dev/safari-utm-stripper/safari-utm-stripper-2.0.4.safariextz

(Autoupdate should also get you the new version).

**Comment by liam-m** [comment]
That seems to be working :)
