### ISSUE TITLE
Publish version 3.0 to Safari Extensions Gallery?

### ISSUE THREAD

**Issue by jonatin** [grahams/safari-utm-stripper#7]
When I install from the extensions gallery I'm getting version 2.0.5.

Could you publish version 3.0 to the gallery?

Thanks!

**Comment by jonatin** [comment]
I also noticed that the 2.0.5 extension had an extra `.Info.plist.swp` file inside. You might want to check that these cruft files are purged before you package the next update.

**Comment by grahams** [comment]
I would love to.  Apple rejected it telling me it has "stability problems" but provided no other details.

**Comment by justinmayer** [comment]
Is there a way to install the current master version without going through the gallery? If so, how would that be done?

**Comment by grahams** [comment]
You can download any of the releases from:
http://www.dosburros.com/dev/safari-utm-stripper/

Once you've downloaded the file launching it from Finder should install it for you.

**Comment by grahams** [comment]
And please, if you find any instability, please let me know..  I have no idea what Apple is referring to.

**Comment by jonatin** [comment]
I've installed 3.0 on several machines, and I'm also running the Safari Tech Previews on a few machines, so if I see any issues I'll report back here.

**Comment by vvsor** [comment]
> You can download any of the releases from:
> http://www.dosburros.com/dev/safari-utm-stripper/

The requested URL /dev/safari-utm-stripper/ was not found on this server.

**Comment by grahams** [comment]
@vvsor Sorry about that, had some files get temporarily lost during a server migration.  You cannot browse that directory, but you can get to the latest release from.  I'm going to submit this release to Apple and see if it passes muster.

http://www.dosburros.com/dev/safari-utm-stripper/safari-utm-stripper-3.0.1.safariextz

**Comment by vvsor** [comment]
@grahams Thanx. I couldn't upgrade utm-stripper up to version 3.0.1 while version 2.0.5 was installed (Safari can’t install this extension: An error occurred while installing the extension “UTM Stripper”)
New version was installed without problems after removing 2.0.5 manually.

**Comment by grahams** [comment]
Apple finally accepted v3.0.1 to the gallery, so you should be able to install it from there if it didn't autoupdate.

**Comment by grahams** [comment]
FYI:  They accepted it without actually notifying me, so I have no idea how long ago they accepted it.  

I would not expect the Safari Extensions Gallery to be around much longer, they are clearly steering devs towards app extensions.  Unfortunately, I haven't yet figured out a way to make an equivalent ObjC/Swift replacement for this extension.   

So if the Extensions Gallery disappears, I don't know whta that means for script extensions or updating.

**Comment by jonatin** [comment]
I can confirm installation of an updated extension from the Gallery on standard Safari and the Developer Preview and that it's working as expected on both of them for a few days now.

Thanks for persevering through the acceptance process.
