### ISSUE TITLE
Does this strip UTM tokens before or after web request is made?

### ISSUE THREAD

**Issue by BillyJoeJimBob** [grahams/safari-utm-stripper#9]
I am curious as to whether the Safari UTM Stripper add-on strips tracking tokens from URLs _before_ a web request is made to actually limit tracking (like the Jon Parise Chrome add-on referenced in github) or does it only do purely aesthetic post-processing  (like the Mihai Parparita add-on).  

Thank you.

**Comment by grahams** [comment]
```(function(window) {
    safari.application.addEventListener("beforeNavigate", function (e) {
        var originalURL = e.url;
```
